import { PetSpeciesDef, PetAccessoryItem, PetSpeciesId } from './petTypes';

export const PET_SPECIES_LIST: PetSpeciesDef[] = [
  {
    id: 'unicorn',
    name: 'Unicorn',
    emoji: '🦄',
    category: 'fantasy',
    tagline: 'Starlight Dreamer',
    description: 'A gentle horned celestial foal with a pastel rainbow mane that shimmers in moonlight.',
    baseColor: '#ffffff',
    secondaryColor: '#fbcfe8',
    accentColor: '#fde047',
    blushColor: '#f472b6',
    eyeColor: '#4f46e5',
    soundType: 'whinny',
    favoriteFood: 'Stardust Blossom',
    favoriteFoodEmoji: '🌸',
    personality: ['Gentle', 'Magical', 'Affectionate'],
  },
  {
    id: 'penguin',
    name: 'Penguin',
    emoji: '🐧',
    category: 'cute',
    tagline: 'Waddling Snowdrop',
    description: 'A round, fluffy baby penguin wearing an invisible coat of warmth that loves cozy garden strolls.',
    baseColor: '#334155',
    secondaryColor: '#ffffff',
    accentColor: '#fb923c',
    blushColor: '#f43f5e',
    eyeColor: '#0f172a',
    soundType: 'peep',
    favoriteFood: 'Glacier Berry',
    favoriteFoodEmoji: '🫐',
    personality: ['Playful', 'Loyal', 'Curious'],
  },
  {
    id: 'dog',
    name: 'Puppy',
    emoji: '🐶',
    category: 'cute',
    tagline: 'Golden Shiba Pup',
    description: 'An enthusiastic and loving pup with curled tail, soft floppy ears, and an endless desire to protect you.',
    baseColor: '#f59e0b',
    secondaryColor: '#fef3c7',
    accentColor: '#ef4444',
    blushColor: '#fb7185',
    eyeColor: '#451a03',
    soundType: 'bark',
    favoriteFood: 'Honey Biscuit',
    favoriteFoodEmoji: '🍪',
    personality: ['Bubbly', 'Devoted', 'Cheerful'],
  },
  {
    id: 'cat',
    name: 'Kitten',
    emoji: '🐱',
    category: 'cute',
    tagline: 'Sakura Calico',
    description: 'A sweet calico kitten who purrs like warm rain and likes curling up at your feet while you write.',
    baseColor: '#fff1f2',
    secondaryColor: '#fb7185',
    accentColor: '#fde047',
    blushColor: '#f43f5e',
    eyeColor: '#059669',
    soundType: 'meow',
    favoriteFood: 'Fresh Salmon Treat',
    favoriteFoodEmoji: '🐟',
    personality: ['Quiet', 'Loving', 'Observant'],
  },
  {
    id: 'alpaca',
    name: 'Alpaca',
    emoji: '🦙',
    category: 'cute',
    tagline: 'Cotton Cloud Sprout',
    description: 'A super fluffy marshmallow alpaca with bouncy wool and a smile that melts away rainy days.',
    baseColor: '#fdf2f8',
    secondaryColor: '#fce7f3',
    accentColor: '#ec4899',
    blushColor: '#f472b6',
    eyeColor: '#374151',
    soundType: 'hum',
    favoriteFood: 'Sweet Clover Grass',
    favoriteFoodEmoji: '🍀',
    personality: ['Peaceful', 'Cuddly', 'Warm'],
  },
  {
    id: 'bunny',
    name: 'Bunny',
    emoji: '🐰',
    category: 'woodland',
    tagline: 'Moon Petal Rabbit',
    description: 'A velvety bunny with long twitching ears who hops beside you and loves gentle ear rubs.',
    baseColor: '#fff7ed',
    secondaryColor: '#fed7aa',
    accentColor: '#fb7185',
    blushColor: '#f472b6',
    eyeColor: '#9d174d',
    soundType: 'purr',
    favoriteFood: 'Crisp Garden Carrot',
    favoriteFoodEmoji: '🥕',
    personality: ['Timid', 'Sweet', 'Attentive'],
  },
  {
    id: 'fox',
    name: 'Fox',
    emoji: '🦊',
    category: 'woodland',
    tagline: 'Kitsune Wanderer',
    description: 'A clever and spirited fox with a giant bushy tail tipped in cream and an aura of twilight magic.',
    baseColor: '#ea580c',
    secondaryColor: '#fff7ed',
    accentColor: '#fbbf24',
    blushColor: '#f97316',
    eyeColor: '#78350f',
    soundType: 'chirp',
    favoriteFood: 'Golden Sweet Plum',
    favoriteFoodEmoji: '🍑',
    personality: ['Clever', 'Playful', 'Soulful'],
  },
  {
    id: 'bear',
    name: 'Bear Cub',
    emoji: '🐻',
    category: 'woodland',
    tagline: 'Honey Hug Cub',
    description: 'A sturdy, cuddly teddy cub with a heart of gold who gives the warmest hugs in the garden.',
    baseColor: '#78350f',
    secondaryColor: '#d97706',
    accentColor: '#fef08a',
    blushColor: '#fb7185',
    eyeColor: '#292524',
    soundType: 'hum',
    favoriteFood: 'Wild Mountain Honey',
    favoriteFoodEmoji: '🍯',
    personality: ['Comforting', 'Sleepy', 'Reliable'],
  },
  {
    id: 'deer',
    name: 'Fawn',
    emoji: '🦌',
    category: 'woodland',
    tagline: 'Blossom Antler Fawn',
    description: 'A graceful little fawn with white flower spots on its back and tiny budding antlers of morning dew.',
    baseColor: '#b45309',
    secondaryColor: '#fef3c7',
    accentColor: '#f472b6',
    blushColor: '#f43f5e',
    eyeColor: '#451a03',
    soundType: 'hum',
    favoriteFood: 'Morning Dew Apple',
    favoriteFoodEmoji: '🍎',
    personality: ['Serene', 'Elegant', 'Calming'],
  },
  {
    id: 'panda',
    name: 'Panda',
    emoji: '🐼',
    category: 'cute',
    tagline: 'Bamboo Dreamer',
    description: 'A round, tumbling baby panda who rolls happily across flower patches and takes peaceful afternoon naps.',
    baseColor: '#f8fafc',
    secondaryColor: '#1e293b',
    accentColor: '#22c55e',
    blushColor: '#fb7185',
    eyeColor: '#0f172a',
    soundType: 'hum',
    favoriteFood: 'Crisp Bamboo Shoot',
    favoriteFoodEmoji: '🎋',
    personality: ['Carefree', 'Wholesome', 'Peaceful'],
  },
  {
    id: 'koala',
    name: 'Koala',
    emoji: '🐨',
    category: 'cute',
    tagline: 'Eucalyptus Snuggler',
    description: 'A fuzzy gray koala with big velvet ears who clings lovingly to your side when you need grounding.',
    baseColor: '#94a3b8',
    secondaryColor: '#f1f5f9',
    accentColor: '#10b981',
    blushColor: '#fb7185',
    eyeColor: '#1e293b',
    soundType: 'purr',
    favoriteFood: 'Sweet Eucalyptus Leaf',
    favoriteFoodEmoji: '🌿',
    personality: ['Sleepy', 'Affectionate', 'Tranquil'],
  },
  {
    id: 'hamster',
    name: 'Hamster',
    emoji: '🐹',
    category: 'cute',
    tagline: 'Chubby Cheek Explorer',
    description: 'A tiny round puffball who stuffs sunflower seeds in its cheeks and scurries with joyful pitter-patters.',
    baseColor: '#fdba74',
    secondaryColor: '#ffffff',
    accentColor: '#ec4899',
    blushColor: '#f43f5e',
    eyeColor: '#18181b',
    soundType: 'squeak',
    favoriteFood: 'Roasted Sunflower Seed',
    favoriteFoodEmoji: '🌻',
    personality: ['Curious', 'Energetic', 'Adorable'],
  },
  {
    id: 'chick',
    name: 'Chick',
    emoji: '🐥',
    category: 'cute',
    tagline: 'Little Sunbeam',
    description: 'A cheerful downy yellow chick that chirps melodic tunes and hops up to peck gentle kisses.',
    baseColor: '#fde047',
    secondaryColor: '#ffffff',
    accentColor: '#f97316',
    blushColor: '#fb7185',
    eyeColor: '#1e293b',
    soundType: 'peep',
    favoriteFood: 'Sweet Golden Corn',
    favoriteFoodEmoji: '🌽',
    personality: ['Joyful', 'Inquisitive', 'Sunny'],
  },
  {
    id: 'dragon',
    name: 'Baby Dragon',
    emoji: '🐉',
    category: 'fantasy',
    tagline: 'Pastel Ember Drake',
    description: 'A tiny winged dragon with shimmering pastel scales that sneezes heart-shaped warm sparkles.',
    baseColor: '#a7f3d0',
    secondaryColor: '#fbcfe8',
    accentColor: '#fbbf24',
    blushColor: '#f43f5e',
    eyeColor: '#7c3aed',
    soundType: 'chirp',
    favoriteFood: 'Ember Spark Berry',
    favoriteFoodEmoji: '🍓',
    personality: ['Spirited', 'Protective', 'Heartwarming'],
  },
  {
    id: 'starsprite',
    name: 'Star Sprite',
    emoji: '✨',
    category: 'fantasy',
    tagline: 'Celestial Wisp',
    description: 'A luminous constellation spirit born from wishes made under the Hanamori Grand Tree.',
    baseColor: '#e0e7ff',
    secondaryColor: '#fdf4ff',
    accentColor: '#facc15',
    blushColor: '#f472b6',
    eyeColor: '#4338ca',
    soundType: 'chirp',
    favoriteFood: 'Moonbeam Drop',
    favoriteFoodEmoji: '⭐',
    personality: ['Ethereal', 'Gentle', 'Luminous'],
  },
  {
    id: 'axolotl',
    name: 'Axolotl',
    emoji: '🫧',
    category: 'cute',
    tagline: 'Water Lily Nibbler',
    description: 'A blushing pink water dragon with petal gills who bobs cheerfully in the fresh garden air.',
    baseColor: '#fbcfe8',
    secondaryColor: '#f472b6',
    accentColor: '#fb7185',
    blushColor: '#e11d48',
    eyeColor: '#1e1b4b',
    soundType: 'purr',
    favoriteFood: 'Water Lily Nectar',
    favoriteFoodEmoji: '🪷',
    personality: ['Sweet', 'Goofy', 'Endearing'],
  },
];

export const PET_NAME_SUGGESTIONS: Record<string, string[]> = {
  unicorn: ['Stardust', 'Celeste', 'Nova', 'Lumi', 'Aurora', 'Miracle'],
  penguin: ['Pebble', 'Waddle', 'Pip', 'Snowy', 'Taro', 'Mumble'],
  dog: ['Mochi', 'Sunny', 'Kona', 'Biscuit', 'Chibi', 'Boba'],
  cat: ['Sakura', 'Matcha', 'Luna', 'Yuki', 'Whiskers', 'Kiki'],
  alpaca: ['Marshmallow', 'Cloudy', 'Fluff', 'Puff', 'Cotton', 'Bao'],
  bunny: ['Clover', 'Bunbun', 'Hoppy', 'Lily', 'Buttercup', 'Peaches'],
  fox: ['Kitsune', 'Ember', 'Rusty', 'Foxy', 'Akira', 'Maple'],
  bear: ['Honey', 'Kuma', 'Teddy', 'Barnaby', 'Oatmeal', 'Cubby'],
  deer: ['Bambi', 'Fawn', 'Willow', 'Chestnut', 'Breeze', 'Flora'],
  panda: ['Bao Bao', 'Pangur', 'Bamboo', 'Oreo', 'Panda-chan', 'Dumpling'],
  koala: ['Euki', 'Kozy', 'Joey', 'Gumnut', 'Snuggles', 'Ozzie'],
  hamster: ['Peanut', 'Nibbles', 'Pip', 'Cheeks', 'Nugget', 'Berry'],
  chick: ['Chirpy', 'Pip', 'Butterball', 'Sunny', 'Peep', 'Dandelion'],
  dragon: ['Draco', 'Ember', 'Ignis', 'Sparky', 'Puff', 'Sapphire'],
  starsprite: ['Cosmo', 'Twinkle', 'Astra', 'Stella', 'Wish', 'Hoshi'],
  axolotl: ['Bubbles', 'Coral', 'Lottie', 'Finny', 'Pufflet', 'Pinky'],
};

export const PET_ACCESSORIES_CATALOG: PetAccessoryItem[] = [
  // Hats
  { id: 'mini_tophat', name: 'Gentleman Top Hat', type: 'hat', emoji: '🎩', description: 'A dashing tiny silk hat for classy strolls.', minLevel: 1 },
  { id: 'blossom_crown', name: 'Cherry Blossom Crown', type: 'hat', emoji: '🌸', description: 'Fresh petals woven with dew and affection.', minLevel: 2 },
  { id: 'straw_hat', name: 'Summer Straw Hat', type: 'hat', emoji: '👒', description: 'Keeps the gentle sun off their cute forehead.', minLevel: 3 },
  { id: 'star_beret', name: 'Pastel Star Beret', type: 'hat', emoji: '⭐', description: 'An artist beret adorned with a gold star.', minLevel: 4 },
  { id: 'froggy_hood', name: 'Froggy Rain Cap', type: 'hat', emoji: '🐸', description: 'Adorable green frog eyes on top.', minLevel: 5 },

  // Bows
  { id: 'pink_satin_bow', name: 'Pink Satin Bow', type: 'bow', emoji: '🎀', description: 'Silky and tied with endless care.', minLevel: 1 },
  { id: 'emerald_ribbon', name: 'Sprout Silk Ribbon', type: 'bow', emoji: '🎗️', description: 'Fresh herbal green ribbon.', minLevel: 2 },
  { id: 'bell_collar', name: 'Golden Jingle Bell', type: 'bow', emoji: '🔔', description: 'Chimes lightly with every little step.', minLevel: 3 },
  { id: 'celestial_ribbon', name: 'Galaxy Chiffon Ribbon', type: 'bow', emoji: '✨', description: 'Glows with soft cosmic dust.', minLevel: 4 },

  // Scarves
  { id: 'knit_scarf', name: 'Warm Knit Scarf', type: 'scarf', emoji: '🧣', description: 'Cozy woolen warmth for chilly twilights.', minLevel: 1 },
  { id: 'sakura_scarf', name: 'Sakura Petal Bandana', type: 'scarf', emoji: '🌸', description: 'Light chiffon decorated with fallen petals.', minLevel: 2 },
  { id: 'warm_bandana', name: 'Sunset Polka Bandana', type: 'scarf', emoji: '🏵️', description: 'Vibrant and full of adventure.', minLevel: 3 },

  // Toys
  { id: 'yarn_ball', name: 'Soft Rainbow Yarn', type: 'toy', emoji: '🧶', description: 'Endless unraveling fun.', minLevel: 1 },
  { id: 'star_squeaker', name: 'Starlight Squeaker', type: 'toy', emoji: '⭐', description: 'Squeaks in high cheerful fifths.', minLevel: 2 },
  { id: 'bell_wand', name: 'Feather Bell Wand', type: 'toy', emoji: '🪄', description: 'Flutters in the garden breeze.', minLevel: 3 },
  { id: 'flower_pinwheel', name: 'Blossom Pinwheel', type: 'toy', emoji: '🎡', description: 'Spins when the pet runs fast.', minLevel: 4 },
];

export const PET_TREATS = [
  { id: 'sakura_mochi', name: 'Sakura Mochi', emoji: '🍡', hungerBonus: 35, happinessBonus: 25, desc: 'Sweet glutinous rice cake wrapped in a preserved cherry leaf.' },
  { id: 'fresh_strawberry', name: 'Garden Strawberry', emoji: '🍓', hungerBonus: 25, happinessBonus: 30, desc: 'Picked fresh from the Hanamori sun patch.' },
  { id: 'honey_biscuit', name: 'Golden Honey Biscuit', emoji: '🍪', hungerBonus: 40, happinessBonus: 20, desc: 'Crunchy and baked with mountain wild honey.' },
  { id: 'star_fruit', name: 'Celestial Star Fruit', emoji: '⭐', hungerBonus: 30, happinessBonus: 40, desc: 'Gleams with crisp, refreshing starlight nectar.' },
  { id: 'bamboo_sprout', name: 'Crisp Bamboo Tender', emoji: '🎋', hungerBonus: 35, happinessBonus: 30, desc: 'Juicy and crunchy, perfect for chewing.' },
];

export const PET_LEVEL_TITLES: Record<number, string> = {
  1: 'New Gentle Friend',
  2: 'Cozy Companion',
  3: 'Devoted Buddy',
  4: 'Garden Guardian',
  5: 'Soulmate Spirit',
  6: 'Legendary Cherished Friend',
};
